// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadSettings():Promise<main.Settings>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function UpdateSettings(arg1:main.Settings):Promise<void>;
